version: '3.4'

services:
  userpermissions.api:
    image: ${DOCKER_REGISTRY-}userpermissionsapi
    build:
      context: .
      dockerfile: src/UserPermissions.Api/Dockerfile
  
  sqlserver-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
  elasticsearch-db:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
  
networks:
   default:
    external: true   
    name: esnetwork

volumes:
    esdata:
        driver: local
